Front-to-back/Models/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Front_to_back.Models
{
    public class Campaign
    {
        public int Id { get; set; }
        [Required]
        public int DiscountPercent { get; set; }
        public List<Product> Products { get; set; }
    }
}

Front-to-back/Areas/AdminArea/Controllers/CampaignController.cs
using Front_to_back.Data;
using Front_to_back.Helpers.Enums;
using Front_to_back.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Front_to_back.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "Admin")]
    public class CampaignController : Controller
    {
        private readonly AppDbContext _context;
        public CampaignController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int page = 1)
        {
            ViewBag.TotalPage = Math.Ceiling((decimal)_context.Campaign.Count() / 2);
            ViewBag.CurrentPage = page;
            List<Campaign> campaigns = _context.Campaign.Skip((page - 1) * 2).Take(2).ToList();

            return View(campaigns);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Campaign campaign)
        {
            List<Campaign> percent = _context.Campaign.Where(hs => hs.DiscountPercent == campaign.DiscountPercent).ToList();
            if (!ModelState.IsValid)
            {
                return View();
            }
            foreach (var item in percent)
            {
                if (item.DiscountPercent == campaign.DiscountPercent)
                {
                    ModelState.AddModelError("DiscountPercent", "Percent already have.Write other percent");
                    return View(campaign);
                }
            }
            if (!(campaign.DiscountPercent >= 0 && campaign.DiscountPercent <= 100))
            {
                ModelState.AddModelError("DiscountPercent", "Percent must be between 0 and 100");
                return View(campaign);
            }
            _context.Campaign.Add(campaign);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int id)
        {
            Campaign campaign = _context.Campaign.FirstOrDefault(c => c.Id == id);
            return View(campaign);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Campaign campaign, int id)
        {
            Campaign percent = _context.Campaign.FirstOrDefault(hs => hs.DiscountPercent == campaign.DiscountPercent);
            if (!ModelState.IsValid)
            {
                return View();
            }
            Campaign existedCampaign = _context.Campaign.FirstOrDefault(c => c.Id == campaign.Id);
            if (existedCampaign == null)
            {
                return NotFound();
            }

            if (percent != null && percent.Id != id)
            {
                ModelState.AddModelError("DiscountPercent", "Percent already have.Write other percent");
                return View(existedCampaign);
            }
            if (!(campaign.DiscountPercent >= 0 && campaign.DiscountPercent <= 100))
            {
                ModelState.AddModelError("DiscountPercent", "Percent must be between 0 and 100");
                return View(campaign);
            }
            existedCampaign.DiscountPercent = campaign.DiscountPercent;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Campaign campaign = _context.Campaign.FirstOrDefault(c => c.Id == id);
            if (campaign == null) return Json(new { status = 404 });

            _context.Campaign.Remove(campaign);
            _context.SaveChanges();

            return Json(new { status = 200 });

        }
    }
}

Front-to-back/Areas/AdminArea/Views/Campaign/Create.cshtml
@model Campaign
@{ ViewData["Title"] = "Create"; }

<div class="container mt-4">
    <h3>Create Campaign Section</h3>
    <form method="post" class="mt-3">
        <div class="mb-3">
            <label asp-for="@Model.DiscountPercent" class="form-label">Discount Percent</label>
            <input type="number" asp-for="@Model.DiscountPercent" class="form-control">
            <span class="mt-2 text text-danger" asp-validation-for="@Model.DiscountPercent"></span>
        </div>


        <button type="submit" class="btn btn-primary">Save</button>
        <a asp-controller="campaign" asp-action="index">

            <i style="font-size:0.875rem; text-decoration:none;" class="btn btn-dark">Back</i>
        </a>
    </form>
</div>
@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}

Front-to-back/Areas/AdminArea/Views/Campaign/Index.cshtml
@model List<Campaign>

@{
    ViewData["Title"] = "Index";
    int count = 0;
}


<div class="container">
    <div class="row">
        <a class="btn btn-primary" asp-controller="Campaign" asp-action="Create">Create</a>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Discount</th>
                    <th scope="col">Settings</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    count++;
                    <tr>
                        <td>@count</td>
                        <td>@item.DiscountPercent</td>
                        <td>
                            <a class="btn btn-danger" asp-area="AdminArea" asp-controller="Campaign" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            <a class="btn btn-success" asp-controller="campaign" asp-action="update" asp-route-id="@item.Id">Update</a>

                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
    <div class="row justify-content-center mt-4">
        <nav aria-label="...">
            <ul class="pagination" style="justify-content:center">

                <li class="page-item @(ViewBag.Currentpage == 1 ? "disabled" : "")">
                    <a class="page-link" asp-controller="campaign" asp-action="index" asp-route-page="@(ViewBag.CurrentPage-1)">Previous</a>
                </li>

                @for (int i = 1; i <= ViewBag.TotalPage; i++)
                {
                    <li class="page-item  @(ViewBag.CurrentPage == i ? "active" : "")" style="pointer-events: @(ViewBag.CurrentPage == i ? "none" : "")"><a class="page-link" asp-controller="campaign" asp-action="index" asp-route-page="@i">@i</a></li>
}

                <li class="page-item @(ViewBag.CurrentPage == ViewBag.TotalPage ? "disabled" : "")">
                    <a class="page-link" asp-controller="campaign" asp-action="index" asp-route-page="@(ViewBag.CurrentPage +1)">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

@section ScriptsJs{

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>$(".delete-item").click(function (e) {
        e.preventDefault()
        console.log($(this).attr("href"))
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                var link = $(this).attr("href");
                fetch(link).then(response => response.json()).then(data => {
                    if (data.status == 200) {
                        location.reload(true)
                    } else {
                        Swal.fire(
                            'Not found!',
                            'Your file can not be deleted.',
                            'Failed'
                        )
                    }
                }
                );
            }
        })
    })</script>
}

Front-to-back/Areas/AdminArea/Views/Campaign/Update.cshtml
@model Campaign
@{
    ViewData["Title"] = "Edit";
}

<div class="container mt-4">
    <h3>Edit Campaign Section</h3>
    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
    <form method="post" class="mt-3">
        <div class="mb-3">
            <label asp-for="@Model.DiscountPercent" class="form-label">Discount Percent</label>
            <input asp-for="@Model.DiscountPercent" class="form-control">
            <span class="mt-2 text text-danger" asp-validation-for="@Model.DiscountPercent"></span>
        </div>


        <button type="submit" class="btn btn-primary">Save</button>
        <a asp-controller="campaign" asp-action="index">

            <i style="font-size:0.875rem; text-decoration:none;" class="btn btn-dark">Back</i>
        </a>
    </form>
</div>



@section ScriptsJs{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}